### PR TITLE
Update sweetgeofeatures.ttl

### PR DESCRIPTION
**Pull request by KellyVance**
Addition of notations as per request from SRA and discussion with @DavidCrosswellGSQ .

Correction of Techtonic to Tectonic.

### CODE REVIEW

**Comment by johnmckellar** [comment]
Nick's typo. If you are looking at the ontology on our website, it is not the one submitted to SWEET. My apologies, not the case!!

**Review by johnmckellar — APPROVED** [review]
OK, approved

**Review by nicholascar — APPROVED** [review]

**Comment by nicholascar** [comment]
I have no problem with any numbers of notations for classes. I presume you want to use them in something like drop-down lists as identifying values, as opposed to labels for which you would use the prefLabel? If this is correct though. why not just use the class ID (i.e. last part of the URI) since that is unique in the ontology?

**Comment by nicholascar** [comment]
This ontology needs to be updated to match changes from the SWEET reviews which we will do once the SWEET PR is accepted and closed.

After those updated from the SWEET process, I will constitute this ontology as a complete profile of SWEET (i.e. use the SWEET URI and declare all the necessary profile parts).

**Pull request merged**
